import { Match, MatchStatus, Team, User, TournamentPredictions, Group } from './types';

// --- 48 Teams based on 2026 PDF Pots & Allocations ---
export const TEAMS: Record<string, Team> = {
  // Pot 1 (Hosts + Top Ranked)
  usa: { id: 'usa', name: 'Estados Unidos', code: 'USA', flag: 'https://flagcdn.com/w160/us.png', ranking: 14 },
  mex: { id: 'mex', name: 'México', code: 'MEX', flag: 'https://flagcdn.com/w160/mx.png', ranking: 15 },
  can: { id: 'can', name: 'Canadá', code: 'CAN', flag: 'https://flagcdn.com/w160/ca.png', ranking: 27 },
  esp: { id: 'esp', name: 'Espanha', code: 'ESP', flag: 'https://flagcdn.com/w160/es.png', ranking: 1 },
  arg: { id: 'arg', name: 'Argentina', code: 'ARG', flag: 'https://flagcdn.com/w160/ar.png', ranking: 2 },
  fra: { id: 'fra', name: 'França', code: 'FRA', flag: 'https://flagcdn.com/w160/fr.png', ranking: 3 },
  eng: { id: 'eng', name: 'Inglaterra', code: 'ENG', flag: 'https://flagcdn.com/w160/gb-eng.png', ranking: 4 },
  bra: { id: 'bra', name: 'Brasil', code: 'BRA', flag: 'https://flagcdn.com/w160/br.png', ranking: 5 },
  por: { id: 'por', name: 'Portugal', code: 'POR', flag: 'https://flagcdn.com/w160/pt.png', ranking: 6 },
  ned: { id: 'ned', name: 'Holanda', code: 'NED', flag: 'https://flagcdn.com/w160/nl.png', ranking: 7 },
  bel: { id: 'bel', name: 'Bélgica', code: 'BEL', flag: 'https://flagcdn.com/w160/be.png', ranking: 8 },
  ger: { id: 'ger', name: 'Alemanha', code: 'GER', flag: 'https://flagcdn.com/w160/de.png', ranking: 9 },

  // Pot 2
  cro: { id: 'cro', name: 'Croácia', code: 'CRO', flag: 'https://flagcdn.com/w160/hr.png', ranking: 10 },
  mar: { id: 'mar', name: 'Marrocos', code: 'MAR', flag: 'https://flagcdn.com/w160/ma.png', ranking: 11 },
  col: { id: 'col', name: 'Colômbia', code: 'COL', flag: 'https://flagcdn.com/w160/co.png', ranking: 13 },
  uru: { id: 'uru', name: 'Uruguai', code: 'URU', flag: 'https://flagcdn.com/w160/uy.png', ranking: 16 },
  sui: { id: 'sui', name: 'Suíça', code: 'SUI', flag: 'https://flagcdn.com/w160/ch.png', ranking: 17 },
  jpn: { id: 'jpn', name: 'Japão', code: 'JPN', flag: 'https://flagcdn.com/w160/jp.png', ranking: 18 },
  sen: { id: 'sen', name: 'Senegal', code: 'SEN', flag: 'https://flagcdn.com/w160/sn.png', ranking: 19 },
  irn: { id: 'irn', name: 'Irã', code: 'IRN', flag: 'https://flagcdn.com/w160/ir.png', ranking: 20 },
  kor: { id: 'kor', name: 'Coreia do Sul', code: 'KOR', flag: 'https://flagcdn.com/w160/kr.png', ranking: 22 },
  ecu: { id: 'ecu', name: 'Equador', code: 'ECU', flag: 'https://flagcdn.com/w160/ec.png', ranking: 23 },
  aut: { id: 'aut', name: 'Áustria', code: 'AUT', flag: 'https://flagcdn.com/w160/at.png', ranking: 24 },
  aus: { id: 'aus', name: 'Austrália', code: 'AUS', flag: 'https://flagcdn.com/w160/au.png', ranking: 26 },

  // Pot 3
  nor: { id: 'nor', name: 'Noruega', code: 'NOR', flag: 'https://flagcdn.com/w160/no.png', ranking: 29 },
  pan: { id: 'pan', name: 'Panamá', code: 'PAN', flag: 'https://flagcdn.com/w160/pa.png', ranking: 30 },
  egy: { id: 'egy', name: 'Egito', code: 'EGY', flag: 'https://flagcdn.com/w160/eg.png', ranking: 34 },
  alg: { id: 'alg', name: 'Argélia', code: 'ALG', flag: 'https://flagcdn.com/w160/dz.png', ranking: 35 },
  sco: { id: 'sco', name: 'Escócia', code: 'SCO', flag: 'https://flagcdn.com/w160/gb-sct.png', ranking: 36 },
  par: { id: 'par', name: 'Paraguai', code: 'PAR', flag: 'https://flagcdn.com/w160/py.png', ranking: 39 },
  tun: { id: 'tun', name: 'Tunísia', code: 'TUN', flag: 'https://flagcdn.com/w160/tn.png', ranking: 40 },
  civ: { id: 'civ', name: 'C. do Marfim', code: 'CIV', flag: 'https://flagcdn.com/w160/ci.png', ranking: 42 },
  uzb: { id: 'uzb', name: 'Uzbequistão', code: 'UZB', flag: 'https://flagcdn.com/w160/uz.png', ranking: 50 },
  qat: { id: 'qat', name: 'Catar', code: 'QAT', flag: 'https://flagcdn.com/w160/qa.png', ranking: 51 },
  ksa: { id: 'ksa', name: 'Arábia Saudita', code: 'KSA', flag: 'https://flagcdn.com/w160/sa.png', ranking: 60 },
  rsa: { id: 'rsa', name: 'África do Sul', code: 'RSA', flag: 'https://flagcdn.com/w160/za.png', ranking: 61 },

  // Pot 4 & Playoffs
  jor: { id: 'jor', name: 'Jordânia', code: 'JOR', flag: 'https://flagcdn.com/w160/jo.png', ranking: 66 },
  cpv: { id: 'cpv', name: 'Cabo Verde', code: 'CPV', flag: 'https://flagcdn.com/w160/cv.png', ranking: 68 },
  gha: { id: 'gha', name: 'Gana', code: 'GHA', flag: 'https://flagcdn.com/w160/gh.png', ranking: 72 },
  cuw: { id: 'cuw', name: 'Curaçao', code: 'CUW', flag: 'https://flagcdn.com/w160/cw.png', ranking: 82 },
  hai: { id: 'hai', name: 'Haiti', code: 'HAI', flag: 'https://flagcdn.com/w160/ht.png', ranking: 84 },
  nzl: { id: 'nzl', name: 'Nova Zelândia', code: 'NZL', flag: 'https://flagcdn.com/w160/nz.png', ranking: 86 },
  
  // Playoff Placeholders
  uefa_a: { id: 'uefa_a', name: 'Repescagem UEFA A', code: 'EUA', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg', ranking: 43 },
  uefa_b: { id: 'uefa_b', name: 'Repescagem UEFA B', code: 'EUB', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg', ranking: 44 },
  uefa_c: { id: 'uefa_c', name: 'Repescagem UEFA C', code: 'EUC', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg', ranking: 45 },
  uefa_d: { id: 'uefa_d', name: 'Repescagem UEFA D', code: 'EUD', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg', ranking: 46 },
  ic_1: { id: 'ic_1', name: 'Repescagem IC 1', code: 'IC1', flag: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/FIFA_logo_without_slogan.svg', ranking: 47 },
  ic_2: { id: 'ic_2', name: 'Repescagem IC 2', code: 'IC2', flag: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/FIFA_logo_without_slogan.svg', ranking: 48 },
};

// --- Official 2026 Schedule (Based on PDF) ---
export const INITIAL_MATCHES: Match[] = [
  // --- GRUPO A ---
  {
    id: 'm1',
    homeTeam: TEAMS.mex,
    awayTeam: TEAMS.rsa,
    date: '2026-06-11T15:00:00',
    group: 'Grupo A',
    location: 'Estádio Azteca, Cidade do México',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm2',
    homeTeam: TEAMS.kor,
    awayTeam: TEAMS.uefa_d,
    date: '2026-06-11T22:00:00',
    group: 'Grupo A',
    location: 'Estádio Akron, Guadalajara',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm25',
    homeTeam: TEAMS.uefa_d,
    awayTeam: TEAMS.rsa,
    date: '2026-06-18T13:00:00',
    group: 'Grupo A',
    location: 'Mercedes-Benz Stadium, Atlanta',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm28',
    homeTeam: TEAMS.mex,
    awayTeam: TEAMS.kor,
    date: '2026-06-18T21:00:00',
    group: 'Grupo A',
    location: 'Estádio Akron, Guadalajara',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm53',
    homeTeam: TEAMS.uefa_d,
    awayTeam: TEAMS.mex,
    date: '2026-06-24T21:00:00',
    group: 'Grupo A',
    location: 'Estádio Azteca, Cidade do México',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm54',
    homeTeam: TEAMS.rsa,
    awayTeam: TEAMS.kor,
    date: '2026-06-24T21:00:00',
    group: 'Grupo A',
    location: 'Estádio BBVA, Monterrey',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO B ---
  {
    id: 'm3',
    homeTeam: TEAMS.can,
    awayTeam: TEAMS.uefa_a,
    date: '2026-06-12T16:00:00',
    group: 'Grupo B',
    location: 'BMO Field, Toronto',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm8',
    homeTeam: TEAMS.qat,
    awayTeam: TEAMS.sui,
    date: '2026-06-13T14:00:00',
    group: 'Grupo B',
    location: 'Levi\'s Stadium, San Francisco',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm26',
    homeTeam: TEAMS.sui,
    awayTeam: TEAMS.uefa_a,
    date: '2026-06-18T14:00:00',
    group: 'Grupo B',
    location: 'SoFi Stadium, Los Angeles',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm27',
    homeTeam: TEAMS.can,
    awayTeam: TEAMS.qat,
    date: '2026-06-18T17:00:00',
    group: 'Grupo B',
    location: 'BC Place, Vancouver',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm51',
    homeTeam: TEAMS.sui,
    awayTeam: TEAMS.can,
    date: '2026-06-24T14:00:00',
    group: 'Grupo B',
    location: 'BC Place, Vancouver',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm52',
    homeTeam: TEAMS.uefa_a,
    awayTeam: TEAMS.qat,
    date: '2026-06-24T14:00:00',
    group: 'Grupo B',
    location: 'Lumen Field, Seattle',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO C ---
  {
    id: 'm7',
    homeTeam: TEAMS.bra,
    awayTeam: TEAMS.mar,
    date: '2026-06-13T18:00:00',
    group: 'Grupo C',
    location: 'Gillette Stadium, Boston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm5',
    homeTeam: TEAMS.hai,
    awayTeam: TEAMS.sco,
    date: '2026-06-13T21:00:00',
    group: 'Grupo C',
    location: 'MetLife Stadium, NY/NJ',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm30',
    homeTeam: TEAMS.sco,
    awayTeam: TEAMS.mar,
    date: '2026-06-19T18:00:00',
    group: 'Grupo C',
    location: 'Gillette Stadium, Boston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm29',
    homeTeam: TEAMS.bra,
    awayTeam: TEAMS.hai,
    date: '2026-06-19T21:00:00',
    group: 'Grupo C',
    location: 'Lincoln Financial Field, Philadelphia',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm49',
    homeTeam: TEAMS.sco,
    awayTeam: TEAMS.bra,
    date: '2026-06-24T18:00:00',
    group: 'Grupo C',
    location: 'Hard Rock Stadium, Miami',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm50',
    homeTeam: TEAMS.mar,
    awayTeam: TEAMS.hai,
    date: '2026-06-24T18:00:00',
    group: 'Grupo C',
    location: 'Mercedes-Benz Stadium, Atlanta',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO D ---
  {
    id: 'm4',
    homeTeam: TEAMS.usa,
    awayTeam: TEAMS.par,
    date: '2026-06-12T18:00:00',
    group: 'Grupo D',
    location: 'SoFi Stadium, Los Angeles',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm6',
    homeTeam: TEAMS.aus,
    awayTeam: TEAMS.uefa_c,
    date: '2026-06-13T21:00:00',
    group: 'Grupo D',
    location: 'BC Place, Vancouver',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm32',
    homeTeam: TEAMS.usa,
    awayTeam: TEAMS.aus,
    date: '2026-06-19T12:00:00',
    group: 'Grupo D',
    location: 'Lumen Field, Seattle',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm31',
    homeTeam: TEAMS.uefa_c,
    awayTeam: TEAMS.par,
    date: '2026-06-19T21:00:00',
    group: 'Grupo D',
    location: 'Levi\'s Stadium, San Francisco',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm59',
    homeTeam: TEAMS.uefa_c,
    awayTeam: TEAMS.usa,
    date: '2026-06-25T19:00:00',
    group: 'Grupo D',
    location: 'SoFi Stadium, Los Angeles',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm60',
    homeTeam: TEAMS.par,
    awayTeam: TEAMS.aus,
    date: '2026-06-25T19:00:00',
    group: 'Grupo D',
    location: 'Levi\'s Stadium, San Francisco',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO E ---
  {
    id: 'm10',
    homeTeam: TEAMS.ger,
    awayTeam: TEAMS.cuw,
    date: '2026-06-14T12:00:00',
    group: 'Grupo E',
    location: 'Lincoln Financial Field, Philadelphia',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm9',
    homeTeam: TEAMS.civ,
    awayTeam: TEAMS.ecu,
    date: '2026-06-14T19:00:00',
    group: 'Grupo E',
    location: 'Lincoln Financial Field, Philadelphia',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm33',
    homeTeam: TEAMS.ger,
    awayTeam: TEAMS.civ,
    date: '2026-06-20T16:00:00',
    group: 'Grupo E',
    location: 'BMO Field, Toronto',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm34',
    homeTeam: TEAMS.ecu,
    awayTeam: TEAMS.cuw,
    date: '2026-06-20T19:00:00',
    group: 'Grupo E',
    location: 'Arrowhead Stadium, Kansas City',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm55',
    homeTeam: TEAMS.cuw,
    awayTeam: TEAMS.civ,
    date: '2026-06-25T16:00:00',
    group: 'Grupo E',
    location: 'Lincoln Financial Field, Philadelphia',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm56',
    homeTeam: TEAMS.ecu,
    awayTeam: TEAMS.ger,
    date: '2026-06-25T16:00:00',
    group: 'Grupo E',
    location: 'MetLife Stadium, NY/NJ',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO F ---
  {
    id: 'm11',
    homeTeam: TEAMS.ned,
    awayTeam: TEAMS.jpn,
    date: '2026-06-14T15:00:00',
    group: 'Grupo F',
    location: 'AT&T Stadium, Dallas',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm12',
    homeTeam: TEAMS.uefa_b,
    awayTeam: TEAMS.tun,
    date: '2026-06-14T18:00:00',
    group: 'Grupo F',
    location: 'Estádio BBVA, Monterrey',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm35',
    homeTeam: TEAMS.ned,
    awayTeam: TEAMS.uefa_b,
    date: '2026-06-20T12:00:00',
    group: 'Grupo F',
    location: 'NRG Stadium, Houston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm36',
    homeTeam: TEAMS.tun,
    awayTeam: TEAMS.jpn,
    date: '2026-06-20T22:00:00',
    group: 'Grupo F',
    location: 'Estádio BBVA, Monterrey',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm57',
    homeTeam: TEAMS.jpn,
    awayTeam: TEAMS.uefa_b,
    date: '2026-06-25T18:00:00',
    group: 'Grupo F',
    location: 'AT&T Stadium, Dallas',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm58',
    homeTeam: TEAMS.tun,
    awayTeam: TEAMS.ned,
    date: '2026-06-25T18:00:00',
    group: 'Grupo F',
    location: 'Arrowhead Stadium, Kansas City',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO G ---
  {
    id: 'm16',
    homeTeam: TEAMS.bel,
    awayTeam: TEAMS.egy,
    date: '2026-06-15T12:00:00',
    group: 'Grupo G',
    location: 'Lumen Field, Seattle',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm15',
    homeTeam: TEAMS.irn,
    awayTeam: TEAMS.nzl,
    date: '2026-06-15T18:00:00',
    group: 'Grupo G',
    location: 'SoFi Stadium, Los Angeles',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm39',
    homeTeam: TEAMS.bel,
    awayTeam: TEAMS.irn,
    date: '2026-06-21T12:00:00',
    group: 'Grupo G',
    location: 'SoFi Stadium, Los Angeles',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm40',
    homeTeam: TEAMS.nzl,
    awayTeam: TEAMS.egy,
    date: '2026-06-21T18:00:00',
    group: 'Grupo G',
    location: 'BC Place, Vancouver',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm63',
    homeTeam: TEAMS.egy,
    awayTeam: TEAMS.irn,
    date: '2026-06-26T20:00:00',
    group: 'Grupo G',
    location: 'Lumen Field, Seattle',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm64',
    homeTeam: TEAMS.nzl,
    awayTeam: TEAMS.bel,
    date: '2026-06-26T20:00:00',
    group: 'Grupo G',
    location: 'BC Place, Vancouver',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO H ---
  {
    id: 'm14',
    homeTeam: TEAMS.esp,
    awayTeam: TEAMS.cpv,
    date: '2026-06-15T12:00:00',
    group: 'Grupo H',
    location: 'Mercedes-Benz Stadium, Atlanta',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm13',
    homeTeam: TEAMS.ksa,
    awayTeam: TEAMS.uru,
    date: '2026-06-15T18:00:00',
    group: 'Grupo H',
    location: 'Hard Rock Stadium, Miami',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm38',
    homeTeam: TEAMS.esp,
    awayTeam: TEAMS.ksa,
    date: '2026-06-21T12:00:00',
    group: 'Grupo H',
    location: 'Mercedes-Benz Stadium, Atlanta',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm37',
    homeTeam: TEAMS.uru,
    awayTeam: TEAMS.cpv,
    date: '2026-06-21T18:00:00',
    group: 'Grupo H',
    location: 'Hard Rock Stadium, Miami',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm65',
    homeTeam: TEAMS.cpv,
    awayTeam: TEAMS.ksa,
    date: '2026-06-26T19:00:00',
    group: 'Grupo H',
    location: 'NRG Stadium, Houston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm66',
    homeTeam: TEAMS.uru,
    awayTeam: TEAMS.esp,
    date: '2026-06-26T18:00:00',
    group: 'Grupo H',
    location: 'Estádio Akron, Guadalajara',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO I ---
  {
    id: 'm17',
    homeTeam: TEAMS.fra,
    awayTeam: TEAMS.sen,
    date: '2026-06-16T15:00:00',
    group: 'Grupo I',
    location: 'MetLife Stadium, NY/NJ',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm18',
    homeTeam: TEAMS.ic_2,
    awayTeam: TEAMS.nor,
    date: '2026-06-16T18:00:00',
    group: 'Grupo I',
    location: 'Gillette Stadium, Boston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm42',
    homeTeam: TEAMS.fra,
    awayTeam: TEAMS.ic_2,
    date: '2026-06-22T17:00:00',
    group: 'Grupo I',
    location: 'Lincoln Financial Field, Philadelphia',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm41',
    homeTeam: TEAMS.nor,
    awayTeam: TEAMS.sen,
    date: '2026-06-22T20:00:00',
    group: 'Grupo I',
    location: 'MetLife Stadium, NY/NJ',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm61',
    homeTeam: TEAMS.nor,
    awayTeam: TEAMS.fra,
    date: '2026-06-26T15:00:00',
    group: 'Grupo I',
    location: 'Gillette Stadium, Boston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm62',
    homeTeam: TEAMS.sen,
    awayTeam: TEAMS.ic_2,
    date: '2026-06-26T15:00:00',
    group: 'Grupo I',
    location: 'BMO Field, Toronto',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO J ---
  {
    id: 'm19',
    homeTeam: TEAMS.arg,
    awayTeam: TEAMS.alg,
    date: '2026-06-16T20:00:00',
    group: 'Grupo J',
    location: 'Arrowhead Stadium, Kansas City',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm20',
    homeTeam: TEAMS.aut,
    awayTeam: TEAMS.jor,
    date: '2026-06-16T21:00:00',
    group: 'Grupo J',
    location: 'Levi\'s Stadium, San Francisco',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm43',
    homeTeam: TEAMS.arg,
    awayTeam: TEAMS.aut,
    date: '2026-06-22T12:00:00',
    group: 'Grupo J',
    location: 'AT&T Stadium, Dallas',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm44',
    homeTeam: TEAMS.jor,
    awayTeam: TEAMS.alg,
    date: '2026-06-22T20:00:00',
    group: 'Grupo J',
    location: 'Levi\'s Stadium, San Francisco',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm69',
    homeTeam: TEAMS.alg,
    awayTeam: TEAMS.aut,
    date: '2026-06-27T21:00:00',
    group: 'Grupo J',
    location: 'Arrowhead Stadium, Kansas City',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm70',
    homeTeam: TEAMS.jor,
    awayTeam: TEAMS.arg,
    date: '2026-06-27T21:00:00',
    group: 'Grupo J',
    location: 'AT&T Stadium, Dallas',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO K ---
  {
    id: 'm23',
    homeTeam: TEAMS.por,
    awayTeam: TEAMS.ic_1,
    date: '2026-06-17T12:00:00',
    group: 'Grupo K',
    location: 'NRG Stadium, Houston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm24',
    homeTeam: TEAMS.uzb,
    awayTeam: TEAMS.col,
    date: '2026-06-17T20:00:00',
    group: 'Grupo K',
    location: 'Estádio Azteca, Cidade do México',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm47',
    homeTeam: TEAMS.por,
    awayTeam: TEAMS.uzb,
    date: '2026-06-23T12:00:00',
    group: 'Grupo K',
    location: 'NRG Stadium, Houston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm48',
    homeTeam: TEAMS.col,
    awayTeam: TEAMS.ic_1,
    date: '2026-06-23T20:00:00',
    group: 'Grupo K',
    location: 'Estádio Akron, Guadalajara',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm71',
    homeTeam: TEAMS.col,
    awayTeam: TEAMS.por,
    date: '2026-06-27T19:30:00',
    group: 'Grupo K',
    location: 'Hard Rock Stadium, Miami',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm72',
    homeTeam: TEAMS.ic_1,
    awayTeam: TEAMS.uzb,
    date: '2026-06-27T19:30:00',
    group: 'Grupo K',
    location: 'Estádio Azteca, Cidade do México',
    status: MatchStatus.SCHEDULED,
  },

  // --- GRUPO L ---
  {
    id: 'm22',
    homeTeam: TEAMS.eng,
    awayTeam: TEAMS.cro,
    date: '2026-06-17T15:00:00',
    group: 'Grupo L',
    location: 'AT&T Stadium, Dallas',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm21',
    homeTeam: TEAMS.gha,
    awayTeam: TEAMS.pan,
    date: '2026-06-17T19:00:00',
    group: 'Grupo L',
    location: 'BMO Field, Toronto',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm45',
    homeTeam: TEAMS.eng,
    awayTeam: TEAMS.gha,
    date: '2026-06-23T16:00:00',
    group: 'Grupo L',
    location: 'Gillette Stadium, Boston',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm46',
    homeTeam: TEAMS.pan,
    awayTeam: TEAMS.cro,
    date: '2026-06-23T19:00:00',
    group: 'Grupo L',
    location: 'BMO Field, Toronto',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm67',
    homeTeam: TEAMS.pan,
    awayTeam: TEAMS.eng,
    date: '2026-06-27T17:00:00',
    group: 'Grupo L',
    location: 'MetLife Stadium, NY/NJ',
    status: MatchStatus.SCHEDULED,
  },
  {
    id: 'm68',
    homeTeam: TEAMS.cro,
    awayTeam: TEAMS.gha,
    date: '2026-06-27T17:00:00',
    group: 'Grupo L',
    location: 'Mercedes-Benz Stadium, Atlanta',
    status: MatchStatus.SCHEDULED,
  },
];

export const OFFICIAL_TOURNAMENT_RESULTS: TournamentPredictions | undefined = undefined; 

export const INITIAL_GROUPS: Group[] = [
  {
    id: 'g1',
    name: 'Amigos da Firma',
    code: 'COPA26',
    adminId: 'f1',
    createdAt: '2025-01-01T10:00:00'
  },
  {
    id: 'g2',
    name: 'Família Silva',
    code: 'FAMILIA',
    adminId: 'me',
    createdAt: '2025-01-02T10:00:00'
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'me',
    name: 'Admin User',
    email: 'admin@gmail.com',
    avatar: 'https://ui-avatars.com/api/?name=Admin&background=10b981&color=fff',
    role: 'ADMIN',
    status: 'ACTIVE',
    groupIds: [], // User needs to select a group first
    activeGroupId: undefined,
    predictions: {},
    totalPoints: 0
  },
  {
    id: 'f1',
    name: 'Carlos Silva',
    email: 'carlos@gmail.com',
    avatar: 'https://picsum.photos/seed/carlos/50/50',
    role: 'USER',
    status: 'ACTIVE',
    groupIds: ['g1', 'g2'],
    activeGroupId: 'g1',
    predictions: {
      'm1': { home: 2, away: 1 }, // MEX vs RSA
      'm2': { home: 1, away: 1 }, // KOR vs UEFA_D
      'm3': { home: 2, away: 0 }, // CAN vs UEFA_A
      'm4': { home: 1, away: 2 }, // USA vs PAR
    },
    tournamentPredictions: {
        topScorer: { player: 'Vinicius Jr', goals: 7 },
        championTeamId: 'bra',
        bestPlayer: 'Neymar',
        bestGoalkeeper: 'Alisson'
    },
    totalPoints: 0 
  },
  {
    id: 'f2',
    name: 'Ana Souza',
    email: 'ana@gmail.com',
    avatar: 'https://picsum.photos/seed/ana/50/50',
    role: 'USER',
    status: 'ACTIVE',
    groupIds: ['g1'],
    activeGroupId: 'g1',
    predictions: {
      'm1': { home: 3, away: 1 },
      'm2': { home: 0, away: 2 },
      'm3': { home: 1, away: 1 },
      'm4': { home: 3, away: 2 },
    },
    tournamentPredictions: {
        topScorer: { player: 'Mbappé', goals: 8 },
        championTeamId: 'fra',
        bestPlayer: 'Mbappé',
        bestGoalkeeper: 'Maignan'
    },
    totalPoints: 0
  },
  {
    id: 'f3',
    name: 'Pedro Rocha',
    email: 'pedro@gmail.com',
    avatar: 'https://picsum.photos/seed/pedro/50/50',
    role: 'USER',
    status: 'ACTIVE',
    groupIds: ['g1'],
    activeGroupId: 'g1',
    predictions: {
      'm1': { home: 0, away: 1 },
      'm2': { home: 1, away: 2 },
      'm3': { home: 2, away: 2 },
      'm4': { home: 0, away: 0 },
    },
    tournamentPredictions: {
        topScorer: { player: 'Kane', goals: 6 },
        championTeamId: 'eng',
        bestPlayer: 'Bellingham',
        bestGoalkeeper: 'Pickford'
    },
    totalPoints: 0
  }
];